
server:
  port: 8088

spring:
  messages:
    basename: messages
  security:
    user:
      name: mymyeong
      password: auto159

springfox:
  documentation:
    auto-startup: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
